# Generated by Django 3.1.3 on 2020-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowmovie',
            name='movieid',
            field=models.IntegerField(default=0, verbose_name='movieid'),
        ),
    ]
