# Generated by Django 3.1.3 on 2020-11-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_shadowmovie_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadowmovie',
            name='movieid',
        ),
    ]
