# Generated by Django 3.1.3 on 2021-02-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video_id',
        ),
    ]
