# Generated by Django 3.1.3 on 2020-12-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201210_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/4.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
