# Generated by Django 3.1.3 on 2020-12-11 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201211_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadowmovie',
            name='genres',
        ),
        migrations.AddField(
            model_name='shadowmovie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=30), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/6.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
