# Generated by Django 3.1.3 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201209_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.FileField(default='avatars/4.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
