# Generated by Django 3.1.4 on 2020-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201211_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='completed',
            field=models.ManyToManyField(default=None, related_name='completed', to='backend.Movie', verbose_name='Completed movie'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='dropped',
            field=models.ManyToManyField(default=None, related_name='dropped', to='backend.Movie', verbose_name='Dropped movie'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='planning',
            field=models.ManyToManyField(default=None, related_name='planning', to='backend.Movie', verbose_name='Movie planning to watch'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='watching',
            field=models.ManyToManyField(default=None, related_name='watching', to='backend.Movie', verbose_name='Movie in presses'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/23.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
