# Generated by Django 3.1.3 on 2020-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201209_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/1.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
