# Generated by Django 3.1.3 on 2020-12-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201209_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
