# Generated by Django 3.1.3 on 2020-12-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_user_id',
        ),
    ]
