# Generated by Django 3.1.3 on 2020-12-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_usercabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.FileField(default='avatars/4.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
