# Generated by Django 3.1.3 on 2020-12-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201210_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/2.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
