# Generated by Django 3.1.3 on 2021-02-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/15.jpg', upload_to='', verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('completed', models.ManyToManyField(blank=True, default=None, related_name='completed', to='movie.Movie', verbose_name='Completed movie')),
                ('dropped', models.ManyToManyField(blank=True, default=None, related_name='dropped', to='movie.Movie', verbose_name='Dropped movie')),
                ('planning', models.ManyToManyField(blank=True, default=None, related_name='planning', to='movie.Movie', verbose_name='Movie planning to watch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watching', models.ManyToManyField(blank=True, default=None, related_name='watching', to='movie.Movie', verbose_name='Movie in presses')),
            ],
        ),
    ]
