# Generated by Django 3.1.3 on 2021-02-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/24.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
