# Generated by Django 3.1.3 on 2021-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/21.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
