# Generated by Django 3.1.3 on 2020-12-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/22.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
