# Generated by Django 3.1.3 on 2021-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210214_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='tg_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/20.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
