# Generated by Django 3.1.3 on 2020-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201220_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/20.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
