# Generated by Django 3.1.3 on 2021-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210215_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=100, null=True, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/24.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
