# Generated by Django 3.1.3 on 2020-12-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201213_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/21.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
