# Generated by Django 3.1.3 on 2020-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_shadowmovie_movie_id'),
        ('accounts', '0004_auto_20201214_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinet',
            name='completed',
            field=models.ManyToManyField(default=None, related_name='completed', to='movie.Movie', verbose_name='Completed movie'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='dropped',
            field=models.ManyToManyField(default=None, related_name='dropped', to='movie.Movie', verbose_name='Dropped movie'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='planning',
            field=models.ManyToManyField(default=None, related_name='planning', to='movie.Movie', verbose_name='Movie planning to watch'),
        ),
        migrations.AddField(
            model_name='usercabinet',
            name='watching',
            field=models.ManyToManyField(default=None, related_name='watching', to='movie.Movie', verbose_name='Movie in presses'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/23.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
