# Generated by Django 3.1.3 on 2021-02-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201220_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/5.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
