# Generated by Django 3.1.3 on 2020-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_shadowmovie_movie_id'),
        ('accounts', '0005_auto_20201217_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/1.jpg', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, related_name='completed', to='movie.Movie', verbose_name='Completed movie'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='dropped',
            field=models.ManyToManyField(blank=True, default=None, related_name='dropped', to='movie.Movie', verbose_name='Dropped movie'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='planning',
            field=models.ManyToManyField(blank=True, default=None, related_name='planning', to='movie.Movie', verbose_name='Movie planning to watch'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='watching',
            field=models.ManyToManyField(blank=True, default=None, related_name='watching', to='movie.Movie', verbose_name='Movie in presses'),
        ),
    ]
