# Generated by Django 3.1.3 on 2020-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_shadowmovie_movie_id'),
        ('accounts', '0006_auto_20201217_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/7.jpg', upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='completed',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='completed', to='movie.Movie', verbose_name='Completed movie'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='dropped',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='dropped', to='movie.Movie', verbose_name='Dropped movie'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='planning',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='planning', to='movie.Movie', verbose_name='Movie planning to watch'),
        ),
        migrations.AlterField(
            model_name='usercabinet',
            name='watching',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='watching', to='movie.Movie', verbose_name='Movie in presses'),
        ),
    ]
