# Generated by Django 3.1.3 on 2020-12-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201217_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='avatar',
            field=models.ImageField(default='avatars/11.jpg', upload_to='', verbose_name='Avatar'),
        ),
    ]
