# Generated by Django 3.1.3 on 2020-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='video',
            field=models.FileField(default=None, upload_to='', verbose_name='Video'),
        ),
    ]
