# Generated by Django 3.1.3 on 2020-11-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='name')),
                ('url', models.CharField(max_length=160, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bucket',
                'verbose_name_plural': 'Buckets',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.bucket', verbose_name='Bucket'),
        ),
    ]
