# Generated by Django 3.1.3 on 2020-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20201113_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='url',
            field=models.CharField(max_length=160, verbose_name='url'),
        ),
    ]
