# Generated by Django 3.1.3 on 2020-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_bucket_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='video',
        ),
        migrations.AddField(
            model_name='bucket_key',
            name='video',
            field=models.FileField(default=None, upload_to='', verbose_name='Video'),
        ),
    ]
