# Generated by Django 3.1.3 on 2020-11-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20201113_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=160, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='url',
        ),
        migrations.AddField(
            model_name='bucket',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.bucket_key', verbose_name='Bucket_key'),
        ),
        migrations.AddField(
            model_name='movie',
            name='key',
            field=models.ManyToManyField(to='main_page.Bucket_key', verbose_name='Bucket_key'),
        ),
    ]
