# Generated by Django 3.1.3 on 2020-11-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20201113_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='urls',
            new_name='key',
        ),
    ]
