# Generated by Django 3.1.3 on 2020-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20201118_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_name',
            field=models.ManyToManyField(to='main_page.VideoName', verbose_name='Video name'),
        ),
    ]
