# Generated by Django 3.1.3 on 2020-11-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20201113_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket_key',
            options={'verbose_name': 'Bucket key', 'verbose_name_plural': 'Bucket keys'},
        ),
        migrations.RenameField(
            model_name='bucket_key',
            old_name='url',
            new_name='Bucket_key',
        ),
    ]
