# Generated by Django 3.1.3 on 2020-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=50, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='origin',
            field=models.CharField(default=None, max_length=30, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Original name'),
        ),
        migrations.AddField(
            model_name='shadowmovie',
            name='director',
            field=models.CharField(default=None, max_length=50, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='shadowmovie',
            name='origin',
            field=models.CharField(default=None, max_length=30, verbose_name='Origin'),
        ),
        migrations.AddField(
            model_name='shadowmovie',
            name='original_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Original name'),
        ),
    ]
