# Generated by Django 3.1.3 on 2020-12-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowmovie',
            name='movie_id',
            field=models.IntegerField(default=0, verbose_name='Movie id'),
        ),
    ]
