# Generated by Django 3.1.3 on 2020-11-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201122_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowUrsls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('seriaurls', models.ManyToManyField(to='movies.ShadowUrsls', verbose_name='ShadowUrsl')),
            ],
        ),
    ]
