# Generated by Django 3.1.3 on 2020-11-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201122_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default=None, upload_to='', verbose_name='Video'),
        ),
    ]
