# Generated by Django 3.1.3 on 2020-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201123_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.ManyToManyField(default=None, to='movies.Video'),
        ),
    ]
